# Generated by Django 6.0.7 on 2026-07-19 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_familiar_estado_solicitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sintomas_reportados', models.TextField()),
                ('nivel_alerta', models.CharField(max_length=20)),
                ('respuesta_ia', models.TextField()),
                ('resumen_medico', models.TextField()),
                ('estado_asignacion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ATENDIDO', 'Atendido')], default='PENDIENTE', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triajes', to='core.paciente')),
            ],
        ),
    ]
