# Generated by Django 6.0.7 on 2026-07-19 23:15

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_triagelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', core.fields.EncryptedTextField(blank=True, null=True)),
                ('firmada', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('triaje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='core.triagelog')),
            ],
        ),
    ]
