# Generated by Django 6.0.7 on 2026-07-21 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_receta'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_id', models.CharField(max_length=20, unique=True)),
                ('categoria', models.CharField(choices=[('Cardiovascular', 'Cardiovascular'), ('Respiratorio', 'Respiratorio'), ('Neurologico', 'Neurologico'), ('Alergias', 'Alergias'), ('Gastrointestinal', 'Gastrointestinal'), ('Traumatologia', 'Traumatologia'), ('Infeccioso', 'Infeccioso'), ('Salud Mental', 'Salud Mental'), ('Pediatrico', 'Pediatrico'), ('General', 'General')], max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField(help_text='Guia clinica completa del protocolo')),
                ('nivel_sugerido', models.CharField(choices=[('critico', 'Critico'), ('medio', 'Medio'), ('bajo', 'Bajo')], max_length=10)),
                ('palabras_clave', models.TextField(help_text='Palabras clave separadas por coma')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['categoria', 'protocol_id'],
            },
        ),
        migrations.AddField(
            model_name='medicoasistente',
            name='carga_trabajo',
            field=models.IntegerField(default=0, help_text='Cantidad de pacientes activos asignados'),
        ),
        migrations.AddField(
            model_name='medicoasistente',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medicoespecialista',
            name='carga_trabajo',
            field=models.IntegerField(default=0, help_text='Cantidad de pacientes activos asignados'),
        ),
        migrations.AddField(
            model_name='medicoespecialista',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='firma_digital',
            field=models.TextField(blank=True, help_text='Firma criptográfica del médico', null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='hash_documento',
            field=models.CharField(blank=True, help_text='SHA-256 del contenido original', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='triagelog',
            name='medico_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triajes_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RAGQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sintomas_query', models.TextField(help_text='Sintomas enviados al motor RAG')),
                ('protocolos_recuperados', models.TextField(help_text='IDs de protocolos recuperados')),
                ('nivel_sugerido_rag', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('triaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rag_queries', to='core.triagelog')),
            ],
        ),
    ]
