# Generated by Django 6.0.7 on 2026-07-22 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_medicalprotocol_medicoasistente_carga_trabajo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenEspecialistaRAG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen_generado', models.TextField(help_text='Resumen clínico técnico generado por el LLM sustentado en bibliografía')),
                ('referencias_bibliograficas', models.TextField(help_text='JSON con las fuentes bibliográficas (libros médicos) recuperadas por el RAG')),
                ('ids_referencias_usadas', models.CharField(blank=True, help_text='IDs de las referencias bibliográficas usadas (ej: BIB-001,BIB-005)', max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('triaje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resumen_especialista', to='core.triagelog')),
            ],
            options={
                'verbose_name': 'Resumen Especialista RAG',
                'verbose_name_plural': 'Resúmenes Especialista RAG',
            },
        ),
    ]
