# Generated by Django 6.0.7 on 2026-07-22 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_samr_us22_resumen_especialista_rag'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroInteraccionBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_paciente', models.TextField(help_text='Mensaje exacto enviado por el paciente')),
                ('respuesta_bot', models.TextField(help_text='Respuesta generada por el asistente de IA')),
                ('hash_inmutable', models.CharField(help_text='SHA-256 hash de (mensaje|respuesta|timestamp) para cumplimiento WORM', max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('triaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interacciones_bot', to='core.triagelog')),
            ],
            options={
                'verbose_name': 'Registro Inmutable de Bot',
                'verbose_name_plural': 'Registros Inmutables de Bot',
                'ordering': ['-timestamp'],
            },
        ),
    ]
