# Generated by Django 6.0.7 on 2026-07-22 02:49

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_samr_us37_registro_inmutable_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrointeraccionbot',
            name='mensaje_paciente',
            field=core.fields.EncryptedTextField(help_text='Mensaje exacto enviado por el paciente'),
        ),
        migrations.AlterField(
            model_name='registrointeraccionbot',
            name='respuesta_bot',
            field=core.fields.EncryptedTextField(help_text='Respuesta generada por el asistente de IA'),
        ),
        migrations.AlterField(
            model_name='triagelog',
            name='respuesta_ia',
            field=core.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='triagelog',
            name='resumen_medico',
            field=core.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='triagelog',
            name='sintomas_reportados',
            field=core.fields.EncryptedTextField(),
        ),
    ]
